### PR TITLE
Fixed import of RepositoryNotFoundError

### PR DESCRIPTION
**Pull request by cmcmaster1**
Currently attempting to import from the wrong place

### CODE REVIEW

**Comment by Blaizzy** [comment]
Thank you very much for the PR @cmcmaster1!

However, this fix throws an error for me on hugginface-hub v0.24.2 but it works fine on v0.25.1.

Could pin it's version on the requirements.txt to v0.25.1?

**Comment by Blaizzy** [comment]
After that is done, it will be ready to merge.

**Comment by Blaizzy** [comment]
Hey 👋

**Comment by cmcmaster1** [comment]
Sorry, just got around to this. Updated the requirements.txt.

**Comment by Blaizzy** [comment]
Thanks a lot!

Will merge as soon as the tests clear.

**Pull request merged**
